server:
  port:  8888

spring:
  rabbitmq:
    host: rabbitmq.thecoffeine.com
    port: 5672
    username: virtuoso
    password: virtuoso
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/coffeine-009/virtuoso-config.git
          basedir: build/virtuoso-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery.thecoffeine.com:8761/eureka/
