server:
  port:  8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coffeine-009/virtuoso-config.git
          basedir: build/virtuoso-config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: virtuoso
    password: virtuoso

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
