server:
  port:  8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/coffeine-009/config.git
          basedir: build/config

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
